import { describe, it, expect } from 'vitest';
import {
  computeOverview, computeDimStats, computeFeedback,
  computeAgentStats, computeGroupStats, computeTrends,
  computeNoteLengthBuckets, computeShortDescBuckets, computeNoiseBuckets,
  parseMonthKey, monthLabel,
} from './analytics';
import type { EnrichedIncident } from './parser';
import type { IncidentScore } from './scorer';

function incident(overrides: Partial<EnrichedIncident> = {}): EnrichedIncident {
  return {
    Number: 'INC0001',
    'Task type': 'Incident',
    Priority: '3 - Moderate',
    State: 'Closed',
    'Short description': '',
    Description: '',
    'Work notes': '',
    'Assignment group': 'Service Desk',
    'Assigned to': 'A. Tech',
    Opened: '2025-03-04 09:00:00',
    Closed: '',
    Channel: 'Phone',
    'Made SLA': true,
    shortDescClean: '',
    descClean: '',
    allNotes: [],
    humanNotes: [],
    isAutoDesc: false,
    ...overrides,
  };
}

function score(overrides: Partial<IncidentScore> = {}): IncidentScore {
  return {
    number: 'INC0001',
    totalScore: 60,
    label: 'Good',
    color: '',
    dimScores: {
      description_quality: 60,
      root_cause: 100,
      steps_documented: 100,
      spelling_grammar: 95,
      professionalism: 80,
    },
    feedback: [],
    noiseRatio: 0,
    noteCount: 2,
    noteChars: 120,
    ...overrides,
  };
}

describe('empty inputs never produce NaN', () => {
  it('computeOverview returns zeroes for no incidents', () => {
    const overview = computeOverview([], []);

    for (const [key, value] of Object.entries(overview)) {
      expect(Number.isNaN(value), `${key} was NaN`).toBe(false);
    }
    expect(overview.total).toBe(0);
    expect(overview.avgScore).toBe(0);
    expect(overview.hasHumanNotesPct).toBe(0);
  });

  it('computeDimStats returns zeroed percentages for no scores', () => {
    const dims = computeDimStats([]);

    expect(dims).toHaveLength(5);
    for (const d of dims) {
      expect(Number.isNaN(d.avg)).toBe(false);
      expect(d.scored0Pct).toBe(0);
      expect(d.scored100Pct).toBe(0);
      expect(d.buckets).toEqual([0, 0, 0, 0]);
    }
  });

  it('bucket helpers return zeroed percentages for empty input', () => {
    for (const buckets of [computeNoteLengthBuckets([]), computeShortDescBuckets([]), computeNoiseBuckets([])]) {
      expect(buckets.length).toBeGreaterThan(0);
      for (const b of buckets) {
        expect(b.count).toBe(0);
        expect(b.pct).toBe(0);
      }
    }
  });

  it('grouping helpers return empty lists rather than NaN rows', () => {
    expect(computeAgentStats([], [])).toEqual([]);
    expect(computeGroupStats([], [])).toEqual([]);
    expect(computeFeedback([])).toEqual([]);
    expect(computeTrends([], [])).toEqual([]);
  });

  it('computeGroupStats does not emit NaN when a group has no matching scores', () => {
    // An incident whose Number has no corresponding score still creates the group.
    const groups = computeGroupStats([incident({ Number: 'INC9999' })], []);

    expect(groups).toHaveLength(1);
    expect(groups[0].count).toBe(0);
    expect(groups[0].avgScore).toBe(0);
    expect(groups[0].avgNoteLength).toBe(0);
    expect(groups[0].avgNoise).toBe(0);
  });
});

describe('computeOverview', () => {
  it('counts labels, root-cause gaps and noise', () => {
    const overview = computeOverview(
      [incident({ Number: 'A', isAutoDesc: true }), incident({ Number: 'B' })],
      [
        score({ number: 'A', label: 'Excellent', totalScore: 90, noteChars: 300, noteCount: 3 }),
        score({
          number: 'B',
          label: 'Critical',
          totalScore: 20,
          noiseRatio: 0.9,
          noteChars: 100,
          noteCount: 0,
          dimScores: { ...score().dimScores, root_cause: 0 },
        }),
      ],
    );

    expect(overview.total).toBe(2);
    expect(overview.avgScore).toBe(55);
    expect(overview.excellent).toBe(1);
    expect(overview.critical).toBe(1);
    expect(overview.noRootCause).toBe(1);
    expect(overview.highNoise).toBe(1);
    expect(overview.autoGenerated).toBe(1);
    expect(overview.emptyNotes).toBe(1);
    expect(overview.avgNoteLength).toBe(200);
    expect(overview.medianNoteLength).toBe(200);
    expect(overview.hasHumanNotesPct).toBe(50);
  });
});

describe('computeAgentStats', () => {
  it('skips agents with fewer than two incidents and sorts by average score', () => {
    const incidents = [
      incident({ Number: 'A', 'Assigned to': 'Low Scorer' }),
      incident({ Number: 'B', 'Assigned to': 'Low Scorer' }),
      incident({ Number: 'C', 'Assigned to': 'High Scorer' }),
      incident({ Number: 'D', 'Assigned to': 'High Scorer' }),
      incident({ Number: 'E', 'Assigned to': 'Only One' }),
    ];
    const scores = [
      score({ number: 'A', totalScore: 20, label: 'Critical' }),
      score({ number: 'B', totalScore: 30, label: 'Poor' }),
      score({ number: 'C', totalScore: 90, label: 'Excellent' }),
      score({ number: 'D', totalScore: 80, label: 'Excellent' }),
      score({ number: 'E', totalScore: 95, label: 'Excellent' }),
    ];

    const agents = computeAgentStats(incidents, scores);

    expect(agents.map(a => a.name)).toEqual(['High Scorer', 'Low Scorer']);
    expect(agents[0].avgScore).toBe(85);
    expect(agents[0].excellent).toBe(2);
    expect(agents[1].avgScore).toBe(25);
  });

  it('buckets unassigned incidents under Unassigned', () => {
    const agents = computeAgentStats(
      [incident({ Number: 'A', 'Assigned to': '' }), incident({ Number: 'B', 'Assigned to': '' })],
      [score({ number: 'A' }), score({ number: 'B' })],
    );

    expect(agents.map(a => a.name)).toEqual(['Unassigned']);
  });
});

describe('computeFeedback', () => {
  it('counts and ranks recurring feedback', () => {
    const items = computeFeedback([
      score({ feedback: ['No root cause documented.', 'Description is empty or too short.'] }),
      score({ feedback: ['No root cause documented.'] }),
      score({ feedback: [] }),
      score({ feedback: ['No root cause documented.'] }),
    ]);

    expect(items[0]).toEqual({ text: 'No root cause documented.', count: 3, pct: 75 });
    expect(items[1]).toEqual({ text: 'Description is empty or too short.', count: 1, pct: 25 });
  });
});

describe('computeTrends', () => {
  it('groups by month in chronological order and skips undated incidents', () => {
    const incidents = [
      incident({ Number: 'A', Opened: '2025-04-02 08:00:00' }),
      incident({ Number: 'B', Opened: '2025-03-11 08:00:00' }),
      incident({ Number: 'C', Opened: '2025-03-28 08:00:00' }),
      incident({ Number: 'D', Opened: '' }),
    ];
    const scores = [
      score({ number: 'A', totalScore: 80, label: 'Excellent' }),
      score({ number: 'B', totalScore: 40, label: 'Poor' }),
      score({ number: 'C', totalScore: 60, label: 'Good' }),
      score({ number: 'D', totalScore: 10, label: 'Critical' }),
    ];

    const trends = computeTrends(incidents, scores);

    expect(trends.map(t => t.month)).toEqual(['2025-03', '2025-04']);
    expect(trends[0].count).toBe(2);
    expect(trends[0].avgScore).toBe(50);
    expect(trends[0].poorOrCriticalPct).toBe(50);
    expect(trends[1].excellentPct).toBe(100);
  });
});

describe('month helpers', () => {
  it('extracts a YYYY-MM key from either separator', () => {
    expect(parseMonthKey('2025-03-04 09:00:00')).toBe('2025-03');
    expect(parseMonthKey('2025/03/04')).toBe('2025-03');
    expect(parseMonthKey('not a date')).toBe('');
    expect(parseMonthKey('')).toBe('');
  });

  it('formats a key as a short month and year', () => {
    expect(monthLabel('2025-03')).toMatch(/2025/);
    expect(monthLabel('')).toBe('');
  });
});
