import type { EnrichedIncident } from './parser';
import type { IncidentScore } from './scorer';

export interface OverviewStats {
  total: number;
  avgScore: number;
  excellent: number;
  good: number;
  poor: number;
  critical: number;
  noRootCause: number;
  highNoise: number;
  autoGenerated: number;
  emptyNotes: number;
  avgNoteLength: number;
  medianNoteLength: number;
  avgNoteCount: number;
  hasHumanNotesPct: number;
}

export interface DimStats {
  name: string;
  label: string;
  weight: number;
  avg: number;
  scored0Pct: number;
  scored100Pct: number;
  buckets: [number, number, number, number];
}

export interface FeedbackItem {
  text: string;
  count: number;
  pct: number;
}

export interface AgentStat {
  name: string;
  count: number;
  avgScore: number;
  excellent: number;
  good: number;
  poor: number;
  critical: number;
}

export interface GroupStat {
  name: string;
  count: number;
  avgScore: number;
  excellent: number;
  critical: number;
  avgNoise: number;
  avgRootCause: number;
  avgNoteLength: number;
}

export interface NoteLengthBucket {
  label: string;
  count: number;
  pct: number;
}

export interface PriorityDist {
  priority: string;
  count: number;
}

export interface StateDist {
  state: string;
  count: number;
}

const DIM_META: { key: keyof import('./scorer').DimScores; label: string; weight: number }[] = [
  { key: 'description_quality', label: 'Description Quality', weight: 25 },
  { key: 'root_cause', label: 'Root Cause', weight: 25 },
  { key: 'steps_documented', label: 'Steps Documented', weight: 20 },
  { key: 'spelling_grammar', label: 'Spelling & Grammar', weight: 15 },
  { key: 'professionalism', label: 'Professionalism', weight: 15 },
];

function median(arr: number[]): number {
  if (arr.length === 0) return 0;
  const sorted = [...arr].sort((a, b) => a - b);
  const mid = Math.floor(sorted.length / 2);
  return sorted.length % 2 ? sorted[mid] : (sorted[mid - 1] + sorted[mid]) / 2;
}

/** Mean of `arr`, or 0 for an empty array (rather than NaN). */
function mean(arr: number[]): number {
  return arr.length ? arr.reduce((a, b) => a + b, 0) / arr.length : 0;
}

/** `part` as a percentage of `whole` to one decimal, or 0 when `whole` is 0. */
function pct(part: number, whole: number): number {
  return whole > 0 ? Math.round((part / whole) * 1000) / 10 : 0;
}

export function computeOverview(incidents: EnrichedIncident[], scores: IncidentScore[]): OverviewStats {
  const total = scores.length;
  const avg = mean;
  const noteLengths = scores.map(s => s.noteChars);
  const noteCounts = scores.map(s => s.noteCount);

  return {
    total,
    avgScore: Math.round(avg(scores.map(s => s.totalScore)) * 10) / 10,
    excellent: scores.filter(s => s.label === 'Excellent').length,
    good: scores.filter(s => s.label === 'Good').length,
    poor: scores.filter(s => s.label === 'Poor').length,
    critical: scores.filter(s => s.label === 'Critical').length,
    noRootCause: scores.filter(s => s.dimScores.root_cause === 0).length,
    highNoise: scores.filter(s => s.noiseRatio > 0.5).length,
    autoGenerated: incidents.filter(i => i.isAutoDesc).length,
    emptyNotes: scores.filter(s => s.noteCount === 0).length,
    avgNoteLength: Math.round(avg(noteLengths)),
    medianNoteLength: Math.round(median(noteLengths)),
    avgNoteCount: Math.round(avg(noteCounts) * 10) / 10,
    hasHumanNotesPct: pct(scores.filter(s => s.noteCount > 0).length, total),
  };
}

export function computeDimStats(scores: IncidentScore[]): DimStats[] {
  return DIM_META.map(({ key, label, weight }) => {
    const vals = scores.map(s => s.dimScores[key]);
    const avg = mean(vals);
    const buckets: [number, number, number, number] = [0, 0, 0, 0];
    for (const v of vals) {
      if (v < 25) buckets[0]++;
      else if (v < 50) buckets[1]++;
      else if (v < 75) buckets[2]++;
      else buckets[3]++;
    }
    return {
      name: key,
      label,
      weight,
      avg: Math.round(avg * 10) / 10,
      scored0Pct: pct(vals.filter(v => v === 0).length, vals.length),
      scored100Pct: pct(vals.filter(v => v === 100).length, vals.length),
      buckets,
    };
  });
}

export function computeFeedback(scores: IncidentScore[]): FeedbackItem[] {
  const counts: Record<string, number> = {};
  for (const s of scores) {
    for (const f of s.feedback) {
      counts[f] = (counts[f] || 0) + 1;
    }
  }
  return Object.entries(counts)
    .map(([text, count]) => ({ text, count, pct: pct(count, scores.length) }))
    .sort((a, b) => b.count - a.count);
}

export function computeAgentStats(incidents: EnrichedIncident[], scores: IncidentScore[]): AgentStat[] {
  const scoreMap = new Map(scores.map(s => [s.number, s]));
  const agents: Record<string, IncidentScore[]> = {};
  for (const inc of incidents) {
    const agent = inc['Assigned to'] || 'Unassigned';
    if (!agents[agent]) agents[agent] = [];
    const s = scoreMap.get(inc.Number);
    if (s) agents[agent].push(s);
  }
  return Object.entries(agents)
    .filter(([, arr]) => arr.length >= 2)
    .map(([name, arr]) => ({
      name,
      count: arr.length,
      avgScore: Math.round(mean(arr.map(s => s.totalScore)) * 10) / 10,
      excellent: arr.filter(s => s.label === 'Excellent').length,
      good: arr.filter(s => s.label === 'Good').length,
      poor: arr.filter(s => s.label === 'Poor').length,
      critical: arr.filter(s => s.label === 'Critical').length,
    }))
    .sort((a, b) => b.avgScore - a.avgScore);
}

export function computeGroupStats(incidents: EnrichedIncident[], scores: IncidentScore[]): GroupStat[] {
  const scoreMap = new Map(scores.map(s => [s.number, s]));
  const groups: Record<string, { scores: IncidentScore[]; incidents: EnrichedIncident[] }> = {};
  for (const inc of incidents) {
    const g = inc['Assignment group'] || 'Unassigned';
    if (!groups[g]) groups[g] = { scores: [], incidents: [] };
    const s = scoreMap.get(inc.Number);
    if (s) groups[g].scores.push(s);
    groups[g].incidents.push(inc);
  }
  return Object.entries(groups)
    .map(([name, { scores: arr }]) => ({
      name,
      count: arr.length,
      avgScore: Math.round(mean(arr.map(s => s.totalScore)) * 10) / 10,
      excellent: arr.filter(s => s.label === 'Excellent').length,
      critical: arr.filter(s => s.label === 'Critical').length,
      avgNoise: Math.round(mean(arr.map(s => s.noiseRatio)) * 100),
      avgRootCause: Math.round(mean(arr.map(s => s.dimScores.root_cause)) * 10) / 10,
      avgNoteLength: Math.round(mean(arr.map(s => s.noteChars))),
    }))
    .sort((a, b) => b.avgScore - a.avgScore);
}

export function computeNoteLengthBuckets(scores: IncidentScore[]): NoteLengthBucket[] {
  const buckets = [
    { label: 'Empty (0)', min: 0, max: 0 },
    { label: 'Minimal (1-50)', min: 1, max: 50 },
    { label: 'Brief (51-200)', min: 51, max: 200 },
    { label: 'Adequate (201-500)', min: 201, max: 500 },
    { label: 'Detailed (500+)', min: 501, max: Infinity },
  ];
  return buckets.map(b => {
    const count = scores.filter(s => s.noteChars >= b.min && s.noteChars <= b.max).length;
    return { label: b.label, count, pct: pct(count, scores.length) };
  });
}

export function computeShortDescBuckets(incidents: EnrichedIncident[]): NoteLengthBucket[] {
  const buckets = [
    { label: 'Empty', test: (i: EnrichedIncident) => i.shortDescClean.length === 0 },
    { label: 'Too Short (<25)', test: (i: EnrichedIncident) => i.shortDescClean.length > 0 && i.shortDescClean.length < 25 },
    { label: 'Brief (25-60)', test: (i: EnrichedIncident) => i.shortDescClean.length >= 25 && i.shortDescClean.length <= 60 },
    { label: 'Good (60+)', test: (i: EnrichedIncident) => i.shortDescClean.length > 60 },
  ];
  return buckets.map(b => {
    const count = incidents.filter(b.test).length;
    return { label: b.label, count, pct: pct(count, incidents.length) };
  });
}

export function computeNoiseBuckets(scores: IncidentScore[]): NoteLengthBucket[] {
  const buckets = [
    { label: 'Clean (<20%)', min: 0, max: 0.2 },
    { label: 'Some (20-50%)', min: 0.2, max: 0.5 },
    { label: 'High (50-80%)', min: 0.5, max: 0.8 },
    { label: 'All Noise (80%+)', min: 0.8, max: 1.01 },
  ];
  return buckets.map(b => {
    const count = scores.filter(s => s.noiseRatio >= b.min && s.noiseRatio < b.max).length;
    return { label: b.label, count, pct: pct(count, scores.length) };
  });
}

export function computePriorityDist(incidents: EnrichedIncident[]): PriorityDist[] {
  const counts: Record<string, number> = {};
  for (const i of incidents) {
    const p = i.Priority || 'Unknown';
    counts[p] = (counts[p] || 0) + 1;
  }
  return Object.entries(counts).map(([priority, count]) => ({ priority, count })).sort((a, b) => b.count - a.count);
}

export function computeStateDist(incidents: EnrichedIncident[]): StateDist[] {
  const counts: Record<string, number> = {};
  for (const i of incidents) {
    const s = i.State || 'Unknown';
    counts[s] = (counts[s] || 0) + 1;
  }
  return Object.entries(counts).map(([state, count]) => ({ state, count })).sort((a, b) => b.count - a.count);
}

export function computeAvgNoteLengthByLabel(scores: IncidentScore[]): { label: string; avg: number; color: string }[] {
  const labels: IncidentScore['label'][] = ['Excellent', 'Good', 'Poor', 'Critical'];
  const colors = ['hsl(152,69%,42%)', 'hsl(43,96%,56%)', 'hsl(16,85%,57%)', 'hsl(0,72%,55%)'];
  return labels.map((l, i) => {
    const arr = scores.filter(s => s.label === l);
    return { label: l, avg: Math.round(mean(arr.map(s => s.noteChars))), color: colors[i] };
  });
}

/** Extract a `YYYY-MM` key from an incident's Opened timestamp, or '' if absent. */
export function parseMonthKey(opened: string): string {
  if (!opened) return '';
  const m = opened.match(/(\d{4})[/-](\d{2})/);
  return m ? `${m[1]}-${m[2]}` : '';
}

/** Render a `YYYY-MM` key as e.g. "Mar 2025". */
export function monthLabel(key: string): string {
  if (!key) return '';
  const [year, month] = key.split('-');
  const d = new Date(Number(year), Number(month) - 1, 1);
  return d.toLocaleString('default', { month: 'short', year: 'numeric' });
}
