import type { EnrichedIncident } from './parser';
import type { IncidentScore } from './scorer';

export interface OverviewStats {
  total: number;
  avgScore: number;
  excellent: number;
  good: number;
  poor: number;
  critical: number;
  noRootCause: number;
  highNoise: number;
  autoGenerated: number;
  emptyNotes: number;
  avgNoteLength: number;
  medianNoteLength: number;
  avgNoteCount: number;
  hasHumanNotesPct: number;
}

export interface DimStats {
  name: string;
  label: string;
  weight: number;
  avg: number;
  scored0Pct: number;
  scored100Pct: number;
  buckets: [number, number, number, number];
}

export interface FeedbackItem {
  text: string;
  count: number;
  pct: number;
}

export interface AgentStat {
  name: string;
  count: number;
  avgScore: number;
  excellent: number;
  good: number;
  poor: number;
  critical: number;
}

export interface GroupStat {
  name: string;
  count: number;
  avgScore: number;
  excellent: number;
  critical: number;
  avgNoise: number;
  avgRootCause: number;
  avgNoteLength: number;
}

export interface NoteLengthBucket {
  label: string;
  count: number;
  pct: number;
}

export interface PriorityDist {
  priority: string;
  count: number;
}

export interface StateDist {
  state: string;
  count: number;
}

const DIM_META: { key: keyof import('./scorer').DimScores; label: string; weight: number }[] = [
  { key: 'description_quality', label: 'Description Quality', weight: 25 },
  { key: 'root_cause', label: 'Root Cause', weight: 25 },
  { key: 'steps_documented', label: 'Steps Documented', weight: 20 },
  { key: 'spelling_grammar', label: 'Spelling & Grammar', weight: 15 },
  { key: 'professionalism', label: 'Professionalism', weight: 15 },
];

function median(arr: number[]): number {
  if (arr.length === 0) return 0;
  const sorted = [...arr].sort((a, b) => a - b);
  const mid = Math.floor(sorted.length / 2);
  return sorted.length % 2 ? sorted[mid] : (sorted[mid - 1] + sorted[mid]) / 2;
}

export function computeOverview(incidents: EnrichedIncident[], scores: IncidentScore[]): OverviewStats {
  const total = scores.length;
  const avg = (arr: number[]) => arr.length ? arr.reduce((a, b) => a + b, 0) / arr.length : 0;
  const noteLengths = scores.map(s => s.noteChars);
  const noteCounts = scores.map(s => s.noteCount);

  return {
    total,
    avgScore: Math.round(avg(scores.map(s => s.totalScore)) * 10) / 10,
    excellent: scores.filter(s => s.label === 'Excellent').length,
    good: scores.filter(s => s.label === 'Good').length,
    poor: scores.filter(s => s.label === 'Poor').length,
    critical: scores.filter(s => s.label === 'Critical').length,
    noRootCause: scores.filter(s => s.dimScores.root_cause === 0).length,
    highNoise: scores.filter(s => s.noiseRatio > 0.5).length,
    autoGenerated: incidents.filter(i => i.isAutoDesc).length,
    emptyNotes: scores.filter(s => s.noteCount === 0).length,
    avgNoteLength: Math.round(avg(noteLengths)),
    medianNoteLength: Math.round(median(noteLengths)),
    avgNoteCount: Math.round(avg(noteCounts) * 10) / 10,
    hasHumanNotesPct: Math.round(scores.filter(s => s.noteCount > 0).length / total * 1000) / 10,
  };
}

export function computeDimStats(scores: IncidentScore[]): DimStats[] {
  return DIM_META.map(({ key, label, weight }) => {
    const vals = scores.map(s => s.dimScores[key]);
    const avg = vals.length ? vals.reduce((a, b) => a + b, 0) / vals.length : 0;
    const buckets: [number, number, number, number] = [0, 0, 0, 0];
    for (const v of vals) {
      if (v < 25) buckets[0]++;
      else if (v < 50) buckets[1]++;
      else if (v < 75) buckets[2]++;
      else buckets[3]++;
    }
    return {
      name: key,
      label,
      weight,
      avg: Math.round(avg * 10) / 10,
      scored0Pct: Math.round(vals.filter(v => v === 0).length / vals.length * 1000) / 10,
      scored100Pct: Math.round(vals.filter(v => v === 100).length / vals.length * 1000) / 10,
      buckets,
    };
  });
}

export function computeFeedback(scores: IncidentScore[]): FeedbackItem[] {
  const counts: Record<string, number> = {};
  for (const s of scores) {
    for (const f of s.feedback) {
      counts[f] = (counts[f] || 0) + 1;
    }
  }
  return Object.entries(counts)
    .map(([text, count]) => ({ text, count, pct: Math.round(count / scores.length * 1000) / 10 }))
    .sort((a, b) => b.count - a.count);
}

export function computeAgentStats(incidents: EnrichedIncident[], scores: IncidentScore[]): AgentStat[] {
  const scoreMap = new Map(scores.map(s => [s.number, s]));
  const agents: Record<string, IncidentScore[]> = {};
  for (const inc of incidents) {
    const agent = inc['Assigned to'] || 'Unassigned';
    if (!agents[agent]) agents[agent] = [];
    const s = scoreMap.get(inc.Number);
    if (s) agents[agent].push(s);
  }
  return Object.entries(agents)
    .filter(([, arr]) => arr.length >= 2)
    .map(([name, arr]) => ({
      name,
      count: arr.length,
      avgScore: Math.round(arr.reduce((a, s) => a + s.totalScore, 0) / arr.length * 10) / 10,
      excellent: arr.filter(s => s.label === 'Excellent').length,
      good: arr.filter(s => s.label === 'Good').length,
      poor: arr.filter(s => s.label === 'Poor').length,
      critical: arr.filter(s => s.label === 'Critical').length,
    }))
    .sort((a, b) => b.avgScore - a.avgScore);
}

export function computeGroupStats(incidents: EnrichedIncident[], scores: IncidentScore[]): GroupStat[] {
  const scoreMap = new Map(scores.map(s => [s.number, s]));
  const groups: Record<string, { scores: IncidentScore[]; incidents: EnrichedIncident[] }> = {};
  for (const inc of incidents) {
    const g = inc['Assignment group'] || 'Unassigned';
    if (!groups[g]) groups[g] = { scores: [], incidents: [] };
    const s = scoreMap.get(inc.Number);
    if (s) groups[g].scores.push(s);
    groups[g].incidents.push(inc);
  }
  return Object.entries(groups)
    .map(([name, { scores: arr }]) => {
      const noteChars = arr.map(s => s.noteChars);
      return {
        name,
        count: arr.length,
        avgScore: Math.round(arr.reduce((a, s) => a + s.totalScore, 0) / arr.length * 10) / 10,
        excellent: arr.filter(s => s.label === 'Excellent').length,
        critical: arr.filter(s => s.label === 'Critical').length,
        avgNoise: Math.round(arr.reduce((a, s) => a + s.noiseRatio, 0) / arr.length * 100),
        avgRootCause: Math.round(arr.reduce((a, s) => a + s.dimScores.root_cause, 0) / arr.length * 10) / 10,
        avgNoteLength: Math.round(noteChars.reduce((a, b) => a + b, 0) / noteChars.length),
      };
    })
    .sort((a, b) => b.avgScore - a.avgScore);
}

export function computeNoteLengthBuckets(scores: IncidentScore[]): NoteLengthBucket[] {
  const buckets = [
    { label: 'Empty (0)', min: 0, max: 0 },
    { label: 'Minimal (1-50)', min: 1, max: 50 },
    { label: 'Brief (51-200)', min: 51, max: 200 },
    { label: 'Adequate (201-500)', min: 201, max: 500 },
    { label: 'Detailed (500+)', min: 501, max: Infinity },
  ];
  return buckets.map(b => {
    const count = scores.filter(s => s.noteChars >= b.min && s.noteChars <= b.max).length;
    return { label: b.label, count, pct: Math.round(count / scores.length * 1000) / 10 };
  });
}

export function computeShortDescBuckets(incidents: EnrichedIncident[]): NoteLengthBucket[] {
  const buckets = [
    { label: 'Empty', test: (i: EnrichedIncident) => i.shortDescClean.length === 0 },
    { label: 'Too Short (<25)', test: (i: EnrichedIncident) => i.shortDescClean.length > 0 && i.shortDescClean.length < 25 },
    { label: 'Brief (25-60)', test: (i: EnrichedIncident) => i.shortDescClean.length >= 25 && i.shortDescClean.length <= 60 },
    { label: 'Good (60+)', test: (i: EnrichedIncident) => i.shortDescClean.length > 60 },
  ];
  return buckets.map(b => {
    const count = incidents.filter(b.test).length;
    return { label: b.label, count, pct: Math.round(count / incidents.length * 1000) / 10 };
  });
}

export function computeNoiseBuckets(scores: IncidentScore[]): NoteLengthBucket[] {
  const buckets = [
    { label: 'Clean (<20%)', min: 0, max: 0.2 },
    { label: 'Some (20-50%)', min: 0.2, max: 0.5 },
    { label: 'High (50-80%)', min: 0.5, max: 0.8 },
    { label: 'All Noise (80%+)', min: 0.8, max: 1.01 },
  ];
  return buckets.map(b => {
    const count = scores.filter(s => s.noiseRatio >= b.min && s.noiseRatio < b.max).length;
    return { label: b.label, count, pct: Math.round(count / scores.length * 1000) / 10 };
  });
}

export function computePriorityDist(incidents: EnrichedIncident[]): PriorityDist[] {
  const counts: Record<string, number> = {};
  for (const i of incidents) {
    const p = i.Priority || 'Unknown';
    counts[p] = (counts[p] || 0) + 1;
  }
  return Object.entries(counts).map(([priority, count]) => ({ priority, count })).sort((a, b) => b.count - a.count);
}

export function computeStateDist(incidents: EnrichedIncident[]): StateDist[] {
  const counts: Record<string, number> = {};
  for (const i of incidents) {
    const s = i.State || 'Unknown';
    counts[s] = (counts[s] || 0) + 1;
  }
  return Object.entries(counts).map(([state, count]) => ({ state, count })).sort((a, b) => b.count - a.count);
}

export function computeAvgNoteLengthByLabel(scores: IncidentScore[]): { label: string; avg: number; color: string }[] {
  const labels: IncidentScore['label'][] = ['Excellent', 'Good', 'Poor', 'Critical'];
  const colors = ['hsl(152,69%,42%)', 'hsl(43,96%,56%)', 'hsl(16,85%,57%)', 'hsl(0,72%,55%)'];
  return labels.map((l, i) => {
    const arr = scores.filter(s => s.label === l);
    const avg = arr.length ? Math.round(arr.reduce((a, s) => a + s.noteChars, 0) / arr.length) : 0;
    return { label: l, avg, color: colors[i] };
  });
}

export interface MonthTrend {
  month: string;
  label: string;
  count: number;
  avgScore: number;
  excellent: number;
  good: number;
  poor: number;
  critical: number;
  excellentPct: number;
  poorOrCriticalPct: number;
  avgDescQuality: number;
  avgRootCause: number;
  avgSteps: number;
  avgSpelling: number;
  avgProfessionalism: number;
  noRootCausePct: number;
  highNoisePct: number;
}

function parseMonthKey(opened: string): string {
  if (!opened) return '';
  const m = opened.match(/(\d{4})[/-](\d{2})/);
  return m ? `${m[1]}-${m[2]}` : '';
}

function monthLabel(key: string): string {
  if (!key) return '';
  const [year, month] = key.split('-');
  const d = new Date(Number(year), Number(month) - 1, 1);
  return d.toLocaleString('default', { month: 'short', year: 'numeric' });
}

export function computeTrends(incidents: EnrichedIncident[], scores: IncidentScore[]): MonthTrend[] {
  const scoreMap = new Map(scores.map(s => [s.number, s]));
  const byMonth: Record<string, { incs: EnrichedIncident[]; scores: IncidentScore[] }> = {};

  for (const inc of incidents) {
    const key = parseMonthKey(inc.Opened);
    if (!key) continue;
    if (!byMonth[key]) byMonth[key] = { incs: [], scores: [] };
    byMonth[key].incs.push(inc);
    const s = scoreMap.get(inc.Number);
    if (s) byMonth[key].scores.push(s);
  }

  const avg = (arr: number[]) => arr.length ? Math.round(arr.reduce((a, b) => a + b, 0) / arr.length * 10) / 10 : 0;

  return Object.entries(byMonth)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([month, { scores: ms }]) => {
      const count = ms.length;
      return {
        month,
        label: monthLabel(month),
        count,
        avgScore: avg(ms.map(s => s.totalScore)),
        excellent: ms.filter(s => s.label === 'Excellent').length,
        good: ms.filter(s => s.label === 'Good').length,
        poor: ms.filter(s => s.label === 'Poor').length,
        critical: ms.filter(s => s.label === 'Critical').length,
        excellentPct: count > 0 ? Math.round(ms.filter(s => s.label === 'Excellent').length / count * 100) : 0,
        poorOrCriticalPct: count > 0 ? Math.round((ms.filter(s => s.label === 'Poor').length + ms.filter(s => s.label === 'Critical').length) / count * 100) : 0,
        avgDescQuality: avg(ms.map(s => s.dimScores.description_quality)),
        avgRootCause: avg(ms.map(s => s.dimScores.root_cause)),
        avgSteps: avg(ms.map(s => s.dimScores.steps_documented)),
        avgSpelling: avg(ms.map(s => s.dimScores.spelling_grammar)),
        avgProfessionalism: avg(ms.map(s => s.dimScores.professionalism)),
        noRootCausePct: count > 0 ? Math.round(ms.filter(s => s.dimScores.root_cause === 0).length / count * 100) : 0,
        highNoisePct: count > 0 ? Math.round(ms.filter(s => s.noiseRatio > 0.5).length / count * 100) : 0,
      };
    });
}
