/**
 * Seeded synthetic incident datasets for generalization tests.
 *
 * Every value is generated ("Service-007", "AG-3", "Channel-Beta"…) — nothing
 * here comes from a real export. Each fixture varies one aspect of the data
 * (which columns exist, cardinality, how dimensions co-occur, journal wording)
 * so tests can show the same code discovering different data correctly.
 */
import * as XLSX from 'xlsx';
import type { IncidentRow } from '../../lib/parser';

export interface SyntheticSpec {
  rows: number;
  seed: number;
  assignmentGroups: string[];
  /** null omits the column entirely. */
  services: string[] | null;
  serviceOfferings: string[] | null;
  channels: string[] | null;
  resolutionCodes: string[] | null;
  /** YYYY-MM months incidents are opened in. */
  months: string[];
  /** Share of rows whose Service / Offering cell is left blank. */
  blankDimensionRate: number;
  /** Journal authors and texts, to vary instance wording. */
  noteAuthors: string[];
  noteTexts: string[];
}

const SHORT_DESCRIPTIONS = [
  'Interface queue backlog on integration node',
  'Batch job failed during nightly load',
  'Certificate expiring on gateway endpoint',
  'Disk space low on reporting server',
  'Connection timeout to downstream system',
];

function mulberry32(seed: number) {
  let a = seed;
  return () => {
    a |= 0; a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const names = (prefix: string, n: number) => Array.from({ length: n }, (_, i) => `${prefix}-${String(i + 1).padStart(3, '0')}`);

const BASE: Omit<SyntheticSpec, 'rows' | 'seed'> = {
  assignmentGroups: names('AG', 5),
  services: names('Service', 6),
  serviceOfferings: names('Offering', 8),
  channels: ['Channel-Alpha', 'Channel-Beta'],
  resolutionCodes: ['Code-1', 'Code-2', 'Code-3'],
  months: ['2026-01', '2026-02', '2026-03'],
  blankDimensionRate: 0.05,
  noteAuthors: ['Analyst-1', 'Analyst-2', 'System'],
  noteTexts: ['Restarted the adapter and verified the queue drained.', 'Task is created by system'],
};

/** The fixture catalogue: each varies one aspect of the data. */
export const FIXTURES = {
  /** Services present, spread over several AGs. */
  A: { ...BASE, rows: 300, seed: 1 },
  /** Different Services, AGs and months from A. */
  B: { ...BASE, rows: 240, seed: 2, assignmentGroups: names('Team', 3), services: names('Svc', 9), serviceOfferings: names('Off', 4), months: ['2025-10', '2025-11'] },
  /** Service and Service offering columns absent. */
  C: { ...BASE, rows: 120, seed: 3, services: null, serviceOfferings: null },
  /** Service ↔ Offering many-to-many with many offerings. */
  D: { ...BASE, rows: 400, seed: 4, services: names('Service', 5), serviceOfferings: names('Offering', 20) },
  /** Service ↔ AG many-to-many with many AGs. */
  E: { ...BASE, rows: 400, seed: 5, assignmentGroups: names('AG', 12), services: names('Service', 8) },
  /** Channel present with arbitrary values. */
  F: { ...BASE, rows: 150, seed: 6, channels: ['Channel-Gamma', 'Channel-Delta', 'Channel-Epsilon', 'Channel-Zeta'] },
  /** Channel column absent. */
  G: { ...BASE, rows: 150, seed: 7, channels: null },
  /** Resolution codes differ from A's. */
  H: { ...BASE, rows: 150, seed: 8, resolutionCodes: ['Resolved-Q', 'Resolved-R', 'Resolved-S', 'Resolved-T'] },
  /** High cardinality. */
  I: { ...BASE, rows: 4000, seed: 9, services: names('Service', 500), serviceOfferings: names('Offering', 200), assignmentGroups: names('AG', 40) },
  /** Journal wording from another instance: none of the configured system patterns match. */
  J: { ...BASE, rows: 150, seed: 10, noteAuthors: ['Automation Bot', 'Analyst-9'], noteTexts: ['Generated by monitoring rule 42', 'Checked the connector logs.'] },
} satisfies Record<string, SyntheticSpec>;

export type FixtureName = keyof typeof FIXTURES;

/** Header-keyed rows for a spec, as a ServiceNow display-name export would have them. */
export function buildRows(spec: SyntheticSpec): IncidentRow[] {
  const rnd = mulberry32(spec.seed);
  const pick = <T,>(list: T[]) => list[Math.floor(rnd() * list.length)];
  const rows: IncidentRow[] = [];

  for (let i = 0; i < spec.rows; i++) {
    const month = pick(spec.months);
    const day = 1 + Math.floor(rnd() * 27);
    const opened = `${month}-${String(day).padStart(2, '0')} ${String(8 + Math.floor(rnd() * 10)).padStart(2, '0')}:15:00`;
    const closed = `${month}-${String(day).padStart(2, '0')} 20:45:30`;
    const notes = [0, 1].map(k =>
      `${opened} - ${spec.noteAuthors[(i + k) % spec.noteAuthors.length]} (Work notes)\n${spec.noteTexts[(i + k) % spec.noteTexts.length]}`,
    ).join('\n');

    const row: IncidentRow = {
      Number: `SYN${String(spec.seed).padStart(2, '0')}${String(i).padStart(6, '0')}`,
      State: 'Closed',
      'Short description': SHORT_DESCRIPTIONS[i % SHORT_DESCRIPTIONS.length],
      Description: `${SHORT_DESCRIPTIONS[i % SHORT_DESCRIPTIONS.length]}. Root cause: synthetic condition ${i % 4}.`,
      'Work notes': notes,
      'Assignment group': pick(spec.assignmentGroups),
      'Assigned to': `Person-${(i % 7) + 1}`,
      Opened: opened,
      Closed: closed,
      'Made SLA': rnd() < 0.8 ? 'true' : 'false',
    };
    if (spec.channels) row.Channel = pick(spec.channels);
    if (spec.services) row.Service = rnd() < spec.blankDimensionRate ? '' : pick(spec.services);
    if (spec.serviceOfferings) row['Service offering'] = rnd() < spec.blankDimensionRate ? '' : pick(spec.serviceOfferings);
    if (spec.resolutionCodes) row['Resolution code'] = pick(spec.resolutionCodes);
    rows.push(row);
  }
  return rows;
}

/** The rows as an .xlsx file, in an ArrayBuffer of this realm, as `File.arrayBuffer()` returns it. */
export function toXlsxBuffer(rows: IncidentRow[]): ArrayBuffer {
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(rows), 'Page 1');
  const written = new Uint8Array(XLSX.write(wb, { type: 'array', bookType: 'xlsx' }));
  const buffer = new ArrayBuffer(written.byteLength);
  new Uint8Array(buffer).set(written);
  return buffer;
}
