/**
 * Versioned registry of instance- and tool-specific text patterns.
 *
 * These patterns are not ServiceNow schema and not dataset values: they encode
 * how one ServiceNow instance and its monitoring tools word automated content
 * (a "System" journal author, FAQ and routing-prediction notes, alert
 * templates). Another instance may word them differently, so they live here,
 * named and versioned, instead of as strings inside the parser.
 *
 * The values were moved here verbatim from `parser.ts`; behaviour is pinned by
 * `parserPatterns.golden.test.ts`. Change a value only together with a version
 * bump — `patterns.test.ts` fails until both are updated.
 *
 * Not here: the scorer's own noise patterns (`scorer.ts`), which include
 * "predicted ag:" and an auto-close phrase. They stay with the scorer, whose
 * source is hash-pinned, and are scorer v2 debt.
 */

export const PATTERN_REGISTRY_VERSION = '1.0.0';

export interface PatternSet {
  id: string;
  version: string;
  /** What a match means. */
  purpose: string;
  /** Where the wording comes from, i.e. what it depends on. */
  sourceContext: 'servicenow-instance' | 'monitoring-tool';
  /** Code that reads the set. */
  consumers: string[];
  /** What happens when nothing in a file matches the set. */
  fallback: string;
  /** Lowercase; matched against lowercased text. */
  values: readonly string[];
}

/** Journal authors whose entries are system-generated. Compared for equality, case-insensitively. */
export const SYSTEM_NOTE_AUTHORS: PatternSet = {
  id: 'instance.systemNoteAuthors',
  version: '1.0.0',
  purpose: 'A work-note entry by one of these authors is system-generated, not human.',
  sourceContext: 'servicenow-instance',
  consumers: ['parser.parseNotes → NoteEntry.isSystem → humanNotes'],
  fallback: 'No author matches: entries count as human unless a system phrase matches (current parser behaviour; scorer v2 debt).',
  values: ['system'],
};

/** Phrases that mark a work-note entry as system-generated wherever they appear in its text. */
export const SYSTEM_NOTE_PHRASES: PatternSet = {
  id: 'instance.systemNotePhrases',
  version: '1.0.0',
  purpose: 'A work-note entry containing one of these phrases is system-generated, not human.',
  sourceContext: 'servicenow-instance',
  consumers: ['parser.parseNotes → NoteEntry.isSystem → humanNotes'],
  fallback: 'No phrase matches: entries count as human unless the author matches (current parser behaviour; scorer v2 debt).',
  values: [
    'sent communication to', 'could not contact', 'task is created by system',
    'escalation is in progress', 'escalate in', 'faq on alerts',
    'predicted ag:', 'attachment added', 'why was this incident created',
    'how is the priority', 'confidence:',
  ],
};

/** Phrases that mark a description as generated by a monitoring alert. */
export const AUTO_DESCRIPTION_KEYWORDS: PatternSet = {
  id: 'monitoring.autoDescriptionKeywords',
  version: '1.0.0',
  purpose: 'A description containing one of these phrases was generated by a monitoring alert.',
  sourceContext: 'monitoring-tool',
  consumers: ['parser.isAutoDescription → EnrichedIncident.isAutoDesc → scorer description quality'],
  fallback: 'No keyword matches: the description is scored as human-written.',
  values: [
    'we have identified unusually', 'alert triggered at', 'usage overview',
    'cluster name', 'namespace :', 'container name:', 'pod name:',
    'document count:', 'conditions met:', 'links for investigation',
  ],
};

/** Every registered set, for auditing and tests. */
export const PATTERN_SETS: readonly PatternSet[] = [SYSTEM_NOTE_AUTHORS, SYSTEM_NOTE_PHRASES, AUTO_DESCRIPTION_KEYWORDS];
